# Generated by Django 4.2.28 on 2026-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
